### ISSUE TITLE
JM leg cit custom term name?

### ISSUE THREAD

**Issue by pomeloy** [Juris-M/jm-styles#26]
First of all, big thanks to @georgd for tackling Austrian/German legal citation styles. 

Not sure if this is a layer 8 issue but how would I go about using the custom term "randnummer" in a footnote? Right now I am avoiding this issue by changing "randnummer" to "line" in https://github.com/Juris-M/jm-styles/blob/8f60707ea32d28369f7d04eddc991b4fa7e8a237/jm-leg-cit-literaturverzeichnis.csl#L47

**Comment by georgd** [comment]
You have to put `rn.` or `Rn.` with the number in the page field. I never remember the proper case...

**Comment by pomeloy** [comment]
Thank you! It's lowercase `rn.`
Do you happen to know the mechanics of how this is handled by Juris-M?

Got it. Unsurprisingly it's part of the CSL-m parsing.
https://github.com/Juris-M/citeproc-js/blob/master/src/load.js#L117
